### PR TITLE
Fix OTA For 64bit Devices

### PR DESCRIPTION
**Pull request by Meninblack007**
In This Way Only One Lib Will Be Copied :)

Signed-off-by: Men_in_black007 <sanyam.53jain@gmail.com>

### CODE REVIEW

**Comment by Meninblack007** [comment]
You Guys Can Try It Out :smile:

**Comment by cuzz1369** [comment]
https://github.com/CandyDevices/device_htc_flounder/commit/ce6b163b591f0f3fae91608248447394f4cbcf10

I just put it in the device side.

**Comment by Meninblack007** [comment]
It's Good :+1:
But I Thought To Fix It Generally.

**Comment by Meninblack007** [comment]
I Got Clean Fix Now.  
Sry For So Much Pulls :stuck_out_tongue_closed_eyes:

**Pull request closed without merging**
